<a href="https://colab.research.google.com/github/chiaramass/UTFPR-Projects/blob/main/Data_Mining/Pre_processamento_Breast_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#importar base de dados
df = pd.read_csv('/content/breast_cancer_missing.csv')
df

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,NaN,0.11840,0.27760,0.3001,0.14710,NaN,...,17.33,184.60,2019.0,0.1622,0.66560,NaN,0.2654,0.4601,0.11890,malignant
1,842517,20.57,NaN,NaN,1326.0,0.08474,NaN,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,19.69,21.25,130.00,1203.0,0.10960,NaN,NaN,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.42450,0.4504,0.2430,NaN,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,NaN,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.86630,0.6869,0.2575,0.6638,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,NaN,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.20500,0.4000,0.1625,0.2364,0.07678,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.2439,0.13890,0.1726,...,26.40,166.10,NaN,0.1410,0.21130,0.4107,0.2216,0.2060,NaN,malignant
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,...,38.25,155.00,1731.0,0.1166,0.19220,0.3215,NaN,0.2572,0.06637,malignant
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,NaN,0.05302,0.1590,...,34.12,126.70,1124.0,0.1139,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,NaN,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,...,39.42,184.60,1821.0,0.1650,0.86810,0.9387,0.2650,0.4087,0.12400,malignant
568,92751,7.76,24.54,47.92,NaN,0.05263,0.04362,0.0000,0.00000,0.1587,...,30.37,59.16,268.6,NaN,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

#1- Analisi exploratoria dos dados

In [ ]:
#formato df
df.shape

(569, 32)

In [ ]:
#informacao sobre os tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sample_id                569 non-null    int64
 1   mean_radius              527 non-null    float64
 2   mean_texture             521 non-null    float64
 3   mean_perimeter           508 non-null    float64
 4   mean_area                502 non-null    float64
 5   mean_smoothness          523 non-null    float64
 6   mean_compactness         510 non-null    float64
 7   mean_concavity           502 non-null    float64
 8   mean_concave_points      514 non-null    float64
 9   mean_symmetry            519 non-null    float64
 10  mean_fractal_dimension   513 non-null    float64
 11  radius_error             511 non-null    float64
 12  texture_error            513 non-null    float64
 13  perimeter_error          505 non-null    float64
 14  area_error               509 non-null    float64
 15  smoothness_error         515 non-null    float64
 16  compactness_error        509 non-null    float64
 17  concavity_error          510 non-null    float64
 18  concave_points_error     524 non-null    float64
 19  symmetry_error           511 non-null    float64
 20  fractal_dimension_error  517 non-null    float64
 21  worst_radius             522 non-null    float64
 22  worst_texture            511 non-null    float64
 23  worst_perimeter          503 non-null    float64
 24  worst_area               509 non-null    float64
 25  worst_smoothness         506 non-null    float64
 26  worst_compactness        516 non-null    float64
 27  worst_concavity          519 non-null    float64
 28  worst_concave_points     517 non-null    float64
 29  worst_symmetry           510 non-null    float64
 30  worst_fractal_dimension  494 non-null    float64
 31  diagnosis                505 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [ ]:
#total de amostras por classe
df['diagnosis'].value_counts()

diagnosis
benign       316
malignant    189
Name: count, dtype: int64

In [ ]:
#pegar amostra aleatoria, seleciona o numero de amostras dentro das parenteses
df.sample(4)

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
414,905680,15.13,29.81,96.71,719.5,0.08320,0.04605,0.04686,0.02739,0.1852,...,36.91,110.10,931.4,0.11480,0.09866,0.1547,0.06575,0.3233,0.06165,malignant
354,901011,11.14,NaN,71.24,NaN,0.07274,0.06064,NaN,0.01471,0.1690,...,15.82,79.62,453.5,0.08864,0.12560,0.1201,0.03922,0.2576,0.07018,benign
375,901303,16.17,16.07,106.30,788.5,0.09880,0.14380,0.06651,0.05397,0.1990,...,19.14,113.10,861.5,0.12350,0.25500,0.2114,0.12510,0.3153,NaN,benign
282,89122,19.40,18.18,127.20,1145.0,0.10370,0.14420,0.16260,0.09464,NaN,...,NaN,152.40,1628.0,0.15180,0.37490,NaN,0.22520,0.3590,NaN,malignant

In [ ]:
#amostra aleatoria mais especifica por classe selecionada
#Colunas ['sample_id', 'diagnosis']
df[['sample_id','diagnosis']].sample(4)

     sample_id diagnosis
208    8810158    benign
206     879804    benign
419     906290    benign
336     897604    benign

In [ ]:
#Agrupar pelas classes
df.groupby('diagnosis')[['sample_id','diagnosis']].sample(6)

     sample_id  diagnosis
537     919812     benign
312   89382602     benign
227   88147102     benign
349     899147     benign
137     868682     benign
102     862965     benign
181     873593  malignant
164    8712289  malignant
190     874858  malignant
205     879523  malignant
6       844359  malignant
27      852781  malignant

In [ ]:
#Diferenca entre dois atributos por classe
#mean_area and worst_area

In [ ]:
df.groupby('diagnosis')[['mean_area', 'worst_area']].agg(['min','max','mean', 'std'])

          mean_area                                 worst_area          \
                min     max        mean         std        min     max
diagnosis
benign        143.5   992.1  464.033684  134.705060      185.2  1032.0
malignant     386.1  2501.0  990.943558  367.001705      553.6  4254.0


                  mean         std
diagnosis
benign      557.475524  162.800566
malignant  1440.750303  595.849372

# 2- Limpeza dos dados
- Missing Values
- selecionar NaN: df.isnull()
-substituir valores NaN: df.fillna()
- substiruir NaN pela media: df.fillna(df.mean(), inplace = True)
- remover NaN: df.dropna(inplace = True)

In [ ]:
# soma quantidade de dados faltantes por atributo
df.isnull().sum()

sample_id                   0
mean_radius                42
mean_texture               48
mean_perimeter             61
mean_area                  67
mean_smoothness            46
mean_compactness           59
mean_concavity             67
mean_concave_points        55
mean_symmetry              50
mean_fractal_dimension     56
radius_error               58
texture_error              56
perimeter_error            64
area_error                 60
smoothness_error           54
compactness_error          60
concavity_error            59
concave_points_error       45
symmetry_error             58
fractal_dimension_error    52
worst_radius               47
worst_texture              58
worst_perimeter            66
worst_area                 60
worst_smoothness           63
worst_compactness          53
worst_concavity            50
worst_concave_points       52
worst_symmetry             59
worst_fractal_dimension    75
diagnosis                  64
dtype: int64

In [ ]:
# selecionar um atributo especifico para ver os valores NaN
df['diagnosis'].isnull().sum()

np.int64(64)

In [ ]:
# remover os dados NaN
df.dropna(subset=['diagnosis'], inplace = True)

In [ ]:
# mostrar os numeros do atributo para confirmar a remoçao
df['diagnosis'].isnull().sum() #agora tem 0 NaN
#df['diagnosis']

np.int64(0)

In [ ]:
#novo formato df
df.shape

(505, 32)

# Tratamento dos dados faltantes nas colunas restantes

In [ ]:
#Atributos que possuem pelo menos um NaN
nan_columns = df.columns[df.isnull().any()].tolist()# a funcao any mostra qualquer valor null encontrado
nan_columns

['mean_radius',
 'mean_texture',
 'mean_perimeter',
 'mean_area',
 'mean_smoothness',
 'mean_compactness',
 'mean_concavity',
 'mean_concave_points',
 'mean_symmetry',
 'mean_fractal_dimension',
 'radius_error',
 'texture_error',
 'perimeter_error',
 'area_error',
 'smoothness_error',
 'compactness_error',
 'concavity_error',
 'concave_points_error',
 'symmetry_error',
 'fractal_dimension_error',
 'worst_radius',
 'worst_texture',
 'worst_perimeter',
 'worst_area',
 'worst_smoothness',
 'worst_compactness',
 'worst_concavity',
 'worst_concave_points',
 'worst_symmetry',
 'worst_fractal_dimension']

In [ ]:
#Substituir os valores faltantes pela media
for col in nan_columns:
  df[col].fillna(df[col].mean(), inplace = True)

/tmp/ipykernel_661/544981809.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace = True)

In [ ]:
#faz a soma dos dados ausentes para todos os atributos
df.isnull().sum()

sample_id                  0
mean_radius                0
mean_texture               0
mean_perimeter             0
mean_area                  0
mean_smoothness            0
mean_compactness           0
mean_concavity             0
mean_concave_points        0
mean_symmetry              0
mean_fractal_dimension     0
radius_error               0
texture_error              0
perimeter_error            0
area_error                 0
smoothness_error           0
compactness_error          0
concavity_error            0
concave_points_error       0
symmetry_error             0
fractal_dimension_error    0
worst_radius               0
worst_texture              0
worst_perimeter            0
worst_area                 0
worst_smoothness           0
worst_compactness          0
worst_concavity            0
worst_concave_points       0
worst_symmetry             0
worst_fractal_dimension    0
diagnosis                  0
dtype: int64

# SimpleImputer

In [ ]:
#importar classe simpleimputer
from sklearn.impute import SimpleImputer

In [ ]:
#faz leitura de base de dados
df = pd.read_csv('/content/breast_cancer_missing.csv')

In [ ]:
df.isnull().sum()

sample_id                   0
mean_radius                38
mean_texture               41
mean_perimeter             52
mean_area                  57
mean_smoothness            42
mean_compactness           54
mean_concavity             61
mean_concave_points        51
mean_symmetry              44
mean_fractal_dimension     51
radius_error               49
texture_error              52
perimeter_error            53
area_error                 54
smoothness_error           47
compactness_error          54
concavity_error            53
concave_points_error       42
symmetry_error             51
fractal_dimension_error    48
worst_radius               43
worst_texture              50
worst_perimeter            53
worst_area                 54
worst_smoothness           54
worst_compactness          46
worst_concavity            44
worst_concave_points       49
worst_symmetry             52
worst_fractal_dimension    68
diagnosis                   0
dtype: int64

In [ ]:
#remover os dados faltantes da classe diagnosis
df.dropna(subset= ['diagnosis'], inplace = True)
df['diagnosis']

0      malignant
2      malignant
3      malignant
4      malignant
5      malignant
         ...
562    malignant
563    malignant
564    malignant
565    malignant
567    malignant
Name: diagnosis, Length: 505, dtype: object

In [ ]:
# retorna nomes das colunas(atributos) com qualquer dados faltante
nan_columns = df.columns[df.isna().any()].tolist()
nan_columns

['mean_radius',
 'mean_texture',
 'mean_perimeter',
 'mean_area',
 'mean_smoothness',
 'mean_compactness',
 'mean_concavity',
 'mean_concave_points',
 'mean_symmetry',
 'mean_fractal_dimension',
 'radius_error',
 'texture_error',
 'perimeter_error',
 'area_error',
 'smoothness_error',
 'compactness_error',
 'concavity_error',
 'concave_points_error',
 'symmetry_error',
 'fractal_dimension_error',
 'worst_radius',
 'worst_texture',
 'worst_perimeter',
 'worst_area',
 'worst_smoothness',
 'worst_compactness',
 'worst_concavity',
 'worst_concave_points',
 'worst_symmetry',
 'worst_fractal_dimension']

In [ ]:
# cria objeto simple imputer
#missing value : indica quale valore deve considerare come mancante
#strategy: indica quale startegia applicare ai dati mancanti.
#In questo caso sostiruirla con la media dei valori presenti (not null) nella stessa colonna
imputer = SimpleImputer(missing_values= np.nan, strategy= 'mean' )

In [ ]:
#Aplica transformacao
#fit(): L'imputer "impara" i parametri necessari dalla colonna (o dalle colonne) specificata.
#fit() : calcolera la media di ogni colonna senza nan
#transform() : dop aver imparato le medie applica la trasformazione dei NaN per la media degli altri valori della colonna
df[nan_columns] = imputer.fit_transform(df[nan_columns])

In [ ]:
#verificaare se ci sono ancora dati null
df.isnull().sum()

sample_id                  0
mean_radius                0
mean_texture               0
mean_perimeter             0
mean_area                  0
mean_smoothness            0
mean_compactness           0
mean_concavity             0
mean_concave_points        0
mean_symmetry              0
mean_fractal_dimension     0
radius_error               0
texture_error              0
perimeter_error            0
area_error                 0
smoothness_error           0
compactness_error          0
concavity_error            0
concave_points_error       0
symmetry_error             0
fractal_dimension_error    0
worst_radius               0
worst_texture              0
worst_perimeter            0
worst_area                 0
worst_smoothness           0
worst_compactness          0
worst_concavity            0
worst_concave_points       0
worst_symmetry             0
worst_fractal_dimension    0
diagnosis                  0
dtype: int64

# Normalização de atributos numéricos


*   StandardScaler : é um pré-processador de dados que transforma os dados de forma que eles tenham uma média de 0 e um desvio padrão de 1. Este é um passo comum na preparação de dados para muitos algoritmos de machine learning, pois pode ajudar a melhorar o desempenho do modelo.

* MinMaxScaler

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Funcao leitura de dados

def readDataset(dataset):
  return pd.read_csv(dataset)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

Limpeza dos dados

In [ ]:
def removeSamples(dataframe, feature):
  dataframe.dropna(subset=[feature], inplace = True)

In [ ]:
#funcao tratamento dos dados faltante nas demais colunas
def fillSamples(dataframe):
  nan_columns=df.columns[df.isna().any()].tolist()
  for col in nan_columns:
    df[col].fillna(df[col].mean(), inplace=True)

In [ ]:
#Função por padronização StandarScaler
#standadizo os valores dos dados para ficarem todos na mesma escala
def stdScaler(dataframe, columns):
  scaler = StandardScaler() #crio um objeto de StandardScaler
  dataframe[columns] = scaler.fit_transform(dataframe[columns])
  # dataframe[columns] : seleciona as counas do df
  # sclare : chamo a função scaler
  # .fit_transform() : faz o fit nos dados (ou seja analisa os dados e calcula a deviação standard (Standard scaler)
  # a parte do tranform: depois dos calculos ele transorma os dados para o desvio padrão
  # (dataframe[columns]): volta os valores escalados nas colunas originarias

In [ ]:
#Função por normalização MinMaxScaler
def minMax(dataframe, columns):
  scaler = MinMaxScaler()
  dataframe[columns] = scaler.fit_transform(dataframe[columns])

# Testando padronização com StandardScaler

In [ ]:
#carregar df chamando a funcao
df = readDataset('/breast_cancer_missing.csv')

In [ ]:
df

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,17.99,10.38,122.80,NaN,0.11840,0.27760,0.3001,0.14710,NaN,...,17.33,184.60,2019.0,0.1622,0.66560,NaN,0.2654,0.4601,0.11890,malignant
1,842517,20.57,NaN,NaN,1326.0,0.08474,NaN,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,19.69,21.25,130.00,1203.0,0.10960,NaN,NaN,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.42450,0.4504,0.2430,NaN,0.08758,malignant
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,NaN,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.86630,0.6869,0.2575,0.6638,0.17300,malignant
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,NaN,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.20500,0.4000,0.1625,0.2364,0.07678,malignant
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.2439,0.13890,0.1726,...,26.40,166.10,NaN,0.1410,0.21130,0.4107,0.2216,0.2060,NaN,malignant
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.1440,0.09791,0.1752,...,38.25,155.00,1731.0,0.1166,0.19220,0.3215,NaN,0.2572,0.06637,malignant
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,NaN,0.05302,0.1590,...,34.12,126.70,1124.0,0.1139,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,NaN,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.15200,0.2397,...,39.42,184.60,1821.0,0.1650,0.86810,0.9387,0.2650,0.4087,0.12400,malignant
568,92751,7.76,24.54,47.92,NaN,0.05263,0.04362,0.0000,0.00000,0.1587,...,30.37,59.16,268.6,NaN,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
#remover as amostras nan
removeSamples(df,'diagnosis')

In [ ]:
df['diagnosis'].isnull().sum()

np.int64(0)

In [ ]:
#armazena nomes das colunas com dados faltantes
nan_columns2 = df.columns[df.isnull().any()].tolist()
nan_columns2

['mean_radius',
 'mean_texture',
 'mean_perimeter',
 'mean_area',
 'mean_smoothness',
 'mean_compactness',
 'mean_concavity',
 'mean_concave_points',
 'mean_symmetry',
 'mean_fractal_dimension',
 'radius_error',
 'texture_error',
 'perimeter_error',
 'area_error',
 'smoothness_error',
 'compactness_error',
 'concavity_error',
 'concave_points_error',
 'symmetry_error',
 'fractal_dimension_error',
 'worst_radius',
 'worst_texture',
 'worst_perimeter',
 'worst_area',
 'worst_smoothness',
 'worst_compactness',
 'worst_concavity',
 'worst_concave_points',
 'worst_symmetry',
 'worst_fractal_dimension']

In [ ]:
#Substituir os dados faltantes pela media
fillSamples(df)

/tmp/ipykernel_1061/1948145816.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [ ]:
df.isnull().sum()

sample_id                  0
mean_radius                0
mean_texture               0
mean_perimeter             0
mean_area                  0
mean_smoothness            0
mean_compactness           0
mean_concavity             0
mean_concave_points        0
mean_symmetry              0
mean_fractal_dimension     0
radius_error               0
texture_error              0
perimeter_error            0
area_error                 0
smoothness_error           0
compactness_error          0
concavity_error            0
concave_points_error       0
symmetry_error             0
fractal_dimension_error    0
worst_radius               0
worst_texture              0
worst_perimeter            0
worst_area                 0
worst_smoothness           0
worst_compactness          0
worst_concavity            0
worst_concave_points       0
worst_symmetry             0
worst_fractal_dimension    0
diagnosis                  0
dtype: int64

# StandardScaler

In [ ]:
#Aplico padronizacao usando a função criada anteriormente do STDScaler
stdScaler(df,nan_columns)

In [ ]:
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,1.085817,-2.172329,1.283164,3.421260e-16,1.622464,3.508049e+00,2.736543e+00,2.562904,1.054117e-15,...,-1.484189,2.356961,2.106997,1.462564,2.759463,0.000000,2.375010,2.859841,2.124614,malignant
2,84300903,1.572820,0.481953,1.591406,1.646896e+00,0.968696,2.809158e-16,3.625689e-16,2.055453,9.665091e-01,...,-0.007520,1.374195,1.533224,0.597244,1.143226,0.886155,2.020424,0.000000,0.210300,malignant
3,84348301,-0.796309,0.269513,-0.652770,-8.114597e-01,3.412898,3.635574e+00,3.625689e-16,1.455497,2.971777e+00,...,0.167159,-0.267728,-0.579187,3.776567,4.104876,2.073151,2.249955,6.292452,5.431268,malignant
4,84358402,1.744704,-1.205359,1.809745,1.929777e+00,0.277781,5.769897e-01,3.625689e-16,1.431710,-2.093352e-02,...,-1.603042,1.365011,1.285206,0.256950,-0.328214,0.633198,0.746131,-0.909796,-0.449808,malignant
5,843786,-0.501242,-0.873269,-0.439141,-5.376068e-01,2.320808,1.329997e+00,8.776898e-01,0.812990,1.034871e+00,...,-0.328065,-0.129039,-0.257318,2.284133,1.816267,1.313273,0.929756,1.821801,2.460780,malignant

# MinMaxScaler

In [ ]:
#carrega df
df = readDataset('/breast_cancer_missing.csv')

# Exemplo de como calcular a mediana de uma coluna
# Por exemplo, para a coluna 'mean_radius':
median_mean_radius = df['mean_radius'].median()
print(f"A mediana de 'mean_radius' é: {median_mean_radius}")

A mediana de 'mean_radius' é: 13.4

In [ ]:
#remove as amostras NaN
removeSamples(df,'diagnosis')

In [ ]:
#armazena o nome das colunas com dados faltantes
nan_columns = df.columns[df.isnull().any()].tolist()
nan_columns

['mean_radius',
 'mean_texture',
 'mean_perimeter',
 'mean_area',
 'mean_smoothness',
 'mean_compactness',
 'mean_concavity',
 'mean_concave_points',
 'mean_symmetry',
 'mean_fractal_dimension',
 'radius_error',
 'texture_error',
 'perimeter_error',
 'area_error',
 'smoothness_error',
 'compactness_error',
 'concavity_error',
 'concave_points_error',
 'symmetry_error',
 'fractal_dimension_error',
 'worst_radius',
 'worst_texture',
 'worst_perimeter',
 'worst_area',
 'worst_smoothness',
 'worst_compactness',
 'worst_concavity',
 'worst_concave_points',
 'worst_symmetry',
 'worst_fractal_dimension']

In [ ]:
#Substitui os dados faltantes pela media
fillSamples(df)

/tmp/ipykernel_1061/1948145816.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [ ]:
# Aplico normalizacao com MinMax
minMax(df, nan_columns)

In [ ]:
df.head()

,sample_id,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,diagnosis
0,842302,0.521037,0.022658,0.552093,0.217283,0.553970,0.792037,0.703140,0.731113,0.381067,...,0.159030,0.668310,0.450698,0.656640,0.619292,0.218722,0.912027,0.598462,0.541370,malignant
2,84300903,0.601496,0.390260,0.602404,0.449417,0.466746,0.260461,0.212302,0.635686,0.509596,...,0.404612,0.508442,0.374508,0.528241,0.385375,0.359744,0.835052,0.263926,0.275856,malignant
3,84348301,0.210090,0.360839,0.236112,0.102906,0.792844,0.811361,0.212302,0.522863,0.776263,...,0.433663,0.241347,0.094008,1.000000,0.814012,0.548642,0.884880,1.000000,1.000000,malignant
4,84358402,0.629893,0.156578,0.638041,0.489290,0.374566,0.347893,0.212302,0.518390,0.378283,...,0.139263,0.506948,0.341575,0.477747,0.172415,0.319489,0.558419,0.157500,0.184300,malignant
5,843786,0.258839,0.202570,0.270980,0.141506,0.647140,0.461996,0.369728,0.402038,0.518687,...,0.351303,0.263908,0.136748,0.778547,0.482784,0.427716,0.598282,0.477035,0.587996,malignant